name: project_template_update

on:
  workflow_dispatch:
  schedule:
    - cron: "0 11 * * MON"

jobs:
  update:
    uses: Stillpoint-Software/shared-workflows/.github/workflows/template_update.yml@main
    with:
      template_repo: https://github.com/stillpoint-software/project.cookiecutter.git
