name: project_template_update

on:
  workflow_dispatch:
    inputs:
        repo_branch:
          description: 'Branch to update'
          required: true
          default: develop
  schedule:
    - cron: "0 7 * * MON"

jobs:
  update:
    uses: Stillpoint-Software/shared-workflows/.github/workflows/template_update.yml@main
    with:
      template_repo: https://github.com/stillpoint-software/project.cookiecutter.git
      repo_branch: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.repo_branch || vars.TemplateUpdateBranch }}